
BEGIN;

CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mid VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    homepage_url VARCHAR NULL,
    last_video_bvid VARCHAR NULL,
    last_dynamic_id VARCHAR NULL,
    last_check_time TIMESTAMPTZ NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS videos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bvid VARCHAR NOT NULL UNIQUE,
    title VARCHAR NOT NULL,
    mid VARCHAR NOT NULL,
    pub_time BIGINT NULL,
    has_subtitle BOOLEAN NOT NULL DEFAULT FALSE,
    has_video BOOLEAN NOT NULL DEFAULT FALSE,
    has_audio BOOLEAN NOT NULL DEFAULT FALSE,
    subtitle_path VARCHAR NULL,
    transcript_text TEXT NULL,
    video_path VARCHAR NULL,
    audio_path VARCHAR NULL,
    status VARCHAR NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    summary_json TEXT NULL,
    doc_url VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dynamics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dynamic_id VARCHAR NOT NULL UNIQUE,
    mid VARCHAR NOT NULL,
    type INTEGER NULL,
    text TEXT NULL,
    image_count INTEGER NOT NULL DEFAULT 0,
    images_path TEXT NULL,
    image_urls TEXT NULL,
    status VARCHAR NOT NULL DEFAULT 'pending',
    push_status VARCHAR NOT NULL DEFAULT 'pending',
    pub_time TIMESTAMPTZ NULL,
    pushed_at TIMESTAMPTZ NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    summary_json TEXT NULL,
    doc_url VARCHAR NULL
);

CREATE TABLE IF NOT EXISTS podcast_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    homepage_url VARCHAR NULL,
    last_episode_eid VARCHAR NULL,
    last_episode_pub_time TIMESTAMPTZ NULL,
    last_response_cursor_json TEXT NULL,
    bootstrap_recent_episodes INTEGER NOT NULL DEFAULT 3,
    last_check_time TIMESTAMPTZ NULL,
    last_success_time TIMESTAMPTZ NULL,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS podcast_episodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eid VARCHAR NOT NULL UNIQUE,
    pid VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    pub_time TIMESTAMPTZ NULL,
    audio_url VARCHAR NOT NULL,
    audio_mime VARCHAR NULL,
    audio_size INTEGER NULL,
    raw_episode_json TEXT NOT NULL,
    local_audio_path TEXT NULL,
    local_transcript_path TEXT NULL,
    local_summary_path TEXT NULL,
    transcript_text TEXT NULL,
    summary_json TEXT NULL,
    doc_url VARCHAR NULL,
    status VARCHAR NOT NULL DEFAULT 'pending',
    push_status VARCHAR NOT NULL DEFAULT 'pending',
    download_attempts INTEGER NOT NULL DEFAULT 0,
    asr_attempts INTEGER NOT NULL DEFAULT 0,
    summary_attempts INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    downloaded_at TIMESTAMPTZ NULL,
    transcribed_at TIMESTAMPTZ NULL,
    summarized_at TIMESTAMPTZ NULL,
    pushed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bvid VARCHAR NOT NULL UNIQUE,
    summary_json TEXT NOT NULL,
    push_status VARCHAR NOT NULL DEFAULT 'pending',
    pushed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR NULL,
    message TEXT NULL,
    context TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS classification_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_name VARCHAR NOT NULL,
    pattern VARCHAR NOT NULL,
    target_folder VARCHAR NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS folder_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_name VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    folder_token VARCHAR NOT NULL,
    folder_path VARCHAR NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS push_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR NOT NULL,
    content_id VARCHAR NOT NULL,
    content_title VARCHAR NULL,
    uploader_name VARCHAR NULL,
    channel VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'success',
    error_message TEXT NULL,
    response_summary TEXT NULL,
    request_payload TEXT NULL,
    response_payload TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS llm_usage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR NULL,
    content_id VARCHAR NULL,
    content_title VARCHAR NULL,
    uploader_name VARCHAR NULL,
    provider VARCHAR NOT NULL,
    model VARCHAR NULL,
    prompt_tokens INTEGER NULL,
    completion_tokens INTEGER NULL,
    total_tokens INTEGER NULL,
    duration_ms INTEGER NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT NULL,
    raw_response TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS runtime_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,
    value TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prompt_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    description TEXT NULL,
    prompt_text TEXT NOT NULL,
    model_profile_id INTEGER NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS llm_model_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    base_url VARCHAR NULL,
    api_key TEXT NULL,
    model_name VARCHAR NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS task_runtime_states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component VARCHAR NOT NULL UNIQUE,
    is_paused BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR NOT NULL DEFAULT 'running',
    last_heartbeat_at TIMESTAMPTZ NULL,
    last_run_at TIMESTAMPTZ NULL,
    last_message TEXT NULL,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_videos_mid ON videos(mid);
CREATE INDEX IF NOT EXISTS idx_videos_status ON videos(status);
CREATE INDEX IF NOT EXISTS idx_dynamics_mid ON dynamics(mid);
CREATE INDEX IF NOT EXISTS idx_dynamics_status ON dynamics(status);
CREATE INDEX IF NOT EXISTS idx_podcast_subscriptions_pid ON podcast_subscriptions(pid);
CREATE INDEX IF NOT EXISTS idx_podcast_subscriptions_active ON podcast_subscriptions(is_active);
CREATE INDEX IF NOT EXISTS idx_podcast_episodes_pid ON podcast_episodes(pid);
CREATE INDEX IF NOT EXISTS idx_podcast_episodes_status ON podcast_episodes(status);
CREATE INDEX IF NOT EXISTS idx_push_history_content ON push_history(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_push_history_channel_created ON push_history(channel, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_llm_usage_content ON llm_usage(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_llm_usage_created_at ON llm_usage(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_runtime_configs_key ON runtime_configs(key);
CREATE INDEX IF NOT EXISTS idx_prompt_templates_key ON prompt_templates(key);
CREATE INDEX IF NOT EXISTS idx_llm_model_profiles_default ON llm_model_profiles(is_default, is_active);
CREATE INDEX IF NOT EXISTS idx_task_runtime_states_component ON task_runtime_states(component);

COMMIT;
